name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.10
          buildozer-cmd: buildozer -v android debug
        # this action runs in a ready environment that supports building APKs

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
